### PR TITLE
Feat/geom notebook

### PR DESCRIPTION
**Pull request by a-cass**
### Description
Add notebook to explore geometries

### Checklist
- [x] Dependencies install correctly in a clean environment and code executes;
- [x] Test coverage extended; created tests fail without the change (if possible)
- [ ] All tests passing;
- [x] Commits follow a [type](https://gist.github.com/brianclements/841ea7bffdb01346392c#type) convention
- [x] Extended the README, documentation and/or docstrings, if necessary;

### CODE REVIEW

**Comment by Lkruitwagen** [comment]
Looking really good - want to add shapely to core client dependencies, and geopandas to an optional `[geo]` dependency group? Then can remove the imports from the notebook etc.

**Comment by joconnor-ecaa** [comment]
@a-cass could you take a look at #18 and make the kernel spec and metadata changes required to run the notebook tests?

**Comment by a-cass** [comment]
@Lkruitwagen `shapely` support added in [feo-client PR #59](https://github.com/transition-zero/feo-client/pull/59)

**Review by joconnor-ecaa — CHANGES_REQUESTED** [review]
Notebook tests fail with (among other known issues)

```FAILED feo-client-examples/4_geometries.ipynb:: - Error - No such kernel: 'feo-client-examples'```

**Review by joconnor-ecaa — APPROVED** [review]

**Pull request merged**
